/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

/**
 *
 * @author yanni
 */
public class VCrearPaquete extends javax.swing.JInternalFrame {

    /**
     * Creates new form VSelecionarAlojamiento
     */
    public VCrearPaquete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLienzo = new javax.swing.JPanel();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtNombrePaquete = new javax.swing.JTextField();
        dcFechaPartida = new com.toedter.calendar.JDateChooser();
        dcFechaRegreso = new com.toedter.calendar.JDateChooser();
        jPanel12 = new javax.swing.JPanel();
        lblAlojamiento = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblVuelo = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblActividad = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cbxLugarPartida = new javax.swing.JComboBox<>();
        cbxLugarDestino = new javax.swing.JComboBox<>();
        cbxPortadaPrincipal = new javax.swing.JComboBox<>();
        cbxPortadaSecundaria = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDatosAlojamiento = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDatosVuelo = new javax.swing.JTextArea();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDatosActividad = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblCantidadRegistros = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCrearPaquete = new javax.swing.JButton();
        btnCambiarAlojamiento = new javax.swing.JButton();
        btnCambiarVuelo = new javax.swing.JButton();
        btnCambiarActividad = new javax.swing.JButton();

        setClosable(true);

        pLienzo.setBackground(new java.awt.Color(250, 250, 250));
        pLienzo.setLayout(new java.awt.BorderLayout());

        btnRight.setBackground(new java.awt.Color(33, 45, 62));
        btnRight.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnRight.setForeground(new java.awt.Color(250, 250, 250));
        btnRight.setText(">");
        btnRight.setContentAreaFilled(false);
        btnRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRight.setOpaque(true);
        pLienzo.add(btnRight, java.awt.BorderLayout.LINE_END);

        btnLeft.setBackground(new java.awt.Color(33, 45, 62));
        btnLeft.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnLeft.setForeground(new java.awt.Color(250, 250, 250));
        btnLeft.setText("<");
        btnLeft.setContentAreaFilled(false);
        btnLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeft.setOpaque(true);
        pLienzo.add(btnLeft, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(207, 10, 10));
        jPanel2.setLayout(new java.awt.GridLayout(2, 4, 1, 1));

        jPanel9.setBackground(new java.awt.Color(250, 250, 250));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAQUETE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        txtNombrePaquete.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtNombrePaquete.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE PAQUETE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel9.add(txtNombrePaquete);

        dcFechaPartida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA DE PARTIDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        dcFechaPartida.setForeground(new java.awt.Color(220, 95, 0));
        dcFechaPartida.setDateFormatString("YYYY-MM-dd");
        dcFechaPartida.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        dcFechaPartida.setOpaque(false);
        jPanel9.add(dcFechaPartida);

        dcFechaRegreso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA DE REGRESO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        dcFechaRegreso.setForeground(new java.awt.Color(220, 95, 0));
        dcFechaRegreso.setDateFormatString("YYYY-MM-dd");
        dcFechaRegreso.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        dcFechaRegreso.setOpaque(false);
        jPanel9.add(dcFechaRegreso);

        jPanel2.add(jPanel9);

        jPanel12.setBackground(new java.awt.Color(250, 250, 250));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALOJAMIENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(lblAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, 288, 300));

        jPanel2.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(250, 250, 250));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VUELO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(lblVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, 288, 300));

        jPanel2.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(250, 250, 250));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACTIVIDAD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(lblActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, 288, 300));

        jPanel2.add(jPanel14);

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL PAQUETE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        cbxLugarPartida.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        cbxLugarPartida.setForeground(new java.awt.Color(220, 95, 0));
        cbxLugarPartida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxLugarPartida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LUGAR DE PARTIDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        cbxLugarPartida.setOpaque(false);
        jPanel4.add(cbxLugarPartida);

        cbxLugarDestino.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        cbxLugarDestino.setForeground(new java.awt.Color(220, 95, 0));
        cbxLugarDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxLugarDestino.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LUGAR DE DESTINO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        cbxLugarDestino.setOpaque(false);
        jPanel4.add(cbxLugarDestino);

        cbxPortadaPrincipal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        cbxPortadaPrincipal.setForeground(new java.awt.Color(220, 95, 0));
        cbxPortadaPrincipal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxPortadaPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PORTADA PRINCIPAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        cbxPortadaPrincipal.setOpaque(false);
        jPanel4.add(cbxPortadaPrincipal);

        cbxPortadaSecundaria.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        cbxPortadaSecundaria.setForeground(new java.awt.Color(220, 95, 0));
        cbxPortadaSecundaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxPortadaSecundaria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PORTADA SECUNDARIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        cbxPortadaSecundaria.setOpaque(false);
        jPanel4.add(cbxPortadaSecundaria);

        jPanel2.add(jPanel4);

        jPanel15.setBackground(new java.awt.Color(250, 250, 250));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS ALOJAMIENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        txaDatosAlojamiento.setColumns(20);
        txaDatosAlojamiento.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaDatosAlojamiento.setRows(5);
        jScrollPane1.setViewportView(txaDatosAlojamiento);

        jPanel15.add(jScrollPane1);

        jPanel2.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(250, 250, 250));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS VUELO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        txaDatosVuelo.setColumns(20);
        txaDatosVuelo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaDatosVuelo.setRows(5);
        jScrollPane2.setViewportView(txaDatosVuelo);

        jPanel16.add(jScrollPane2);

        jPanel2.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(250, 250, 250));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS ACTIVIDAD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        txaDatosActividad.setColumns(20);
        txaDatosActividad.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaDatosActividad.setRows(5);
        jScrollPane3.setViewportView(txaDatosActividad);

        jPanel17.add(jScrollPane3);

        jPanel2.add(jPanel17);

        pLienzo.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("jLabel1");
        jPanel1.add(lblTitulo);

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        lblCantidadRegistros.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblCantidadRegistros.setForeground(new java.awt.Color(207, 10, 10));
        lblCantidadRegistros.setText("jLabel2");
        jPanel5.add(lblCantidadRegistros);

        lblNombreUsuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(207, 10, 10));
        lblNombreUsuario.setText("jLabel2");
        jPanel5.add(lblNombreUsuario);

        lblEmail.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(207, 10, 10));
        lblEmail.setText("jLabel2");
        jPanel5.add(lblEmail);

        jPanel1.add(jPanel5);

        pLienzo.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnCrearPaquete.setBackground(new java.awt.Color(33, 45, 62));
        btnCrearPaquete.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnCrearPaquete.setForeground(new java.awt.Color(250, 250, 250));
        btnCrearPaquete.setText("CREAR PAQUETE");
        btnCrearPaquete.setContentAreaFilled(false);
        btnCrearPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearPaquete.setOpaque(true);
        jPanel3.add(btnCrearPaquete);

        btnCambiarAlojamiento.setBackground(new java.awt.Color(33, 45, 62));
        btnCambiarAlojamiento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnCambiarAlojamiento.setForeground(new java.awt.Color(250, 250, 250));
        btnCambiarAlojamiento.setText("CAMBIAR ALOJAMIENTO");
        btnCambiarAlojamiento.setContentAreaFilled(false);
        btnCambiarAlojamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarAlojamiento.setOpaque(true);
        jPanel3.add(btnCambiarAlojamiento);

        btnCambiarVuelo.setBackground(new java.awt.Color(33, 45, 62));
        btnCambiarVuelo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnCambiarVuelo.setForeground(new java.awt.Color(250, 250, 250));
        btnCambiarVuelo.setText("CAMBIAR VUELO");
        btnCambiarVuelo.setContentAreaFilled(false);
        btnCambiarVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarVuelo.setOpaque(true);
        jPanel3.add(btnCambiarVuelo);

        btnCambiarActividad.setBackground(new java.awt.Color(33, 45, 62));
        btnCambiarActividad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnCambiarActividad.setForeground(new java.awt.Color(250, 250, 250));
        btnCambiarActividad.setText("CAMBIAR ACTIVIDAD");
        btnCambiarActividad.setContentAreaFilled(false);
        btnCambiarActividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarActividad.setOpaque(true);
        jPanel3.add(btnCambiarActividad);

        pLienzo.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarActividad;
    public javax.swing.JButton btnCambiarAlojamiento;
    public javax.swing.JButton btnCambiarVuelo;
    public javax.swing.JButton btnCrearPaquete;
    public javax.swing.JButton btnLeft;
    public javax.swing.JButton btnRight;
    public javax.swing.JComboBox<String> cbxLugarDestino;
    public javax.swing.JComboBox<String> cbxLugarPartida;
    public javax.swing.JComboBox<String> cbxPortadaPrincipal;
    public javax.swing.JComboBox<String> cbxPortadaSecundaria;
    public com.toedter.calendar.JDateChooser dcFechaPartida;
    public com.toedter.calendar.JDateChooser dcFechaRegreso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblActividad;
    public javax.swing.JLabel lblAlojamiento;
    public javax.swing.JLabel lblCantidadRegistros;
    public javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblNombreUsuario;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lblVuelo;
    public javax.swing.JPanel pLienzo;
    public javax.swing.JTextArea txaDatosActividad;
    public javax.swing.JTextArea txaDatosAlojamiento;
    public javax.swing.JTextArea txaDatosVuelo;
    public javax.swing.JTextField txtNombrePaquete;
    // End of variables declaration//GEN-END:variables
}
