/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

/**
 *
 * @author yanni
 */
public class VCrearAlojamiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form VSelecionarAlojamiento
     */
    public VCrearAlojamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNumeroPersonas = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxIdHotel = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbxPortadaPrincipal = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbxPortadaSecundaria = new javax.swing.JComboBox<>();
        lblPortadaSecundaria = new javax.swing.JLabel();
        lblPortadaPrincipal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCostoAlojamiento = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDatosExtra = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtNumeroHabitaciones = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(42, 39, 41));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel2.setBackground(new java.awt.Color(207, 10, 10));
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jButton2.setBackground(new java.awt.Color(250, 250, 250));
        jButton2.setForeground(new java.awt.Color(250, 250, 250));
        jButton2.setText("VER DETALLE");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        jButton2.setContentAreaFilled(false);
        jButton2.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 180, 50));

        jPanel4.setBackground(new java.awt.Color(42, 39, 41));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel5.setBackground(new java.awt.Color(192, 27, 54));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        btnCrear.setBackground(new java.awt.Color(250, 250, 250));
        btnCrear.setForeground(new java.awt.Color(250, 250, 250));
        btnCrear.setText("CREAR");
        btnCrear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        btnCrear.setContentAreaFilled(false);
        jPanel4.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 180, 50));

        jPanel5.setBackground(new java.awt.Color(42, 39, 41));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel8.setBackground(new java.awt.Color(192, 27, 54));
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jButton4.setBackground(new java.awt.Color(250, 250, 250));
        jButton4.setForeground(new java.awt.Color(250, 250, 250));
        jButton4.setText("ACTUALIZAR");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        jButton4.setContentAreaFilled(false);
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 180, 50));

        jPanel6.setBackground(new java.awt.Color(42, 39, 41));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel11.setBackground(new java.awt.Color(192, 27, 54));
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jButton5.setBackground(new java.awt.Color(250, 250, 250));
        jButton5.setForeground(new java.awt.Color(250, 250, 250));
        jButton5.setText("ELIMINAR ");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 180, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1000, 90));

        jLabel20.setBackground(new java.awt.Color(207, 10, 10));
        jLabel20.setOpaque(true);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("CREAR ALOJAMIENTO");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel21.setBackground(new java.awt.Color(207, 10, 10));
        jLabel21.setOpaque(true);
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        txtNumeroPersonas.setBackground(new java.awt.Color(33, 45, 62));
        txtNumeroPersonas.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtNumeroPersonas.setForeground(new java.awt.Color(220, 95, 0));
        txtNumeroPersonas.setBorder(null);
        txtNumeroPersonas.setCaretColor(new java.awt.Color(220, 95, 0));
        txtNumeroPersonas.setOpaque(false);
        jPanel1.add(txtNumeroPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 270, 40));

        jSeparator1.setBackground(new java.awt.Color(207, 10, 10));
        jSeparator1.setForeground(new java.awt.Color(220, 95, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 10));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 48, 36));

        jLabel9.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(10, 10, 10));
        jLabel9.setText("ID HOTEL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 310, -1));

        cbxIdHotel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        cbxIdHotel.setForeground(new java.awt.Color(220, 95, 0));
        cbxIdHotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxIdHotel.setBorder(null);
        cbxIdHotel.setOpaque(false);
        jPanel1.add(cbxIdHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 310, 50));

        jLabel14.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(10, 10, 10));
        jLabel14.setText("NUMERO DE PERSONAS");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(10, 10, 10));
        jLabel16.setText("PORTADA PRINCIPAL");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 310, -1));

        cbxPortadaPrincipal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        cbxPortadaPrincipal.setForeground(new java.awt.Color(220, 95, 0));
        cbxPortadaPrincipal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxPortadaPrincipal.setBorder(null);
        cbxPortadaPrincipal.setOpaque(false);
        jPanel1.add(cbxPortadaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 310, 50));

        jLabel17.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(10, 10, 10));
        jLabel17.setText("PORTADA SECUNDARIA");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 310, -1));

        cbxPortadaSecundaria.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        cbxPortadaSecundaria.setForeground(new java.awt.Color(220, 95, 0));
        cbxPortadaSecundaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxPortadaSecundaria.setBorder(null);
        cbxPortadaSecundaria.setOpaque(false);
        jPanel1.add(cbxPortadaSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 310, 50));
        jPanel1.add(lblPortadaSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 310, 110));
        jPanel1.add(lblPortadaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 310, 110));

        jLabel18.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(10, 10, 10));
        jLabel18.setText("COSTO ALOJAMIENTO");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtCostoAlojamiento.setBackground(new java.awt.Color(33, 45, 62));
        txtCostoAlojamiento.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtCostoAlojamiento.setForeground(new java.awt.Color(220, 95, 0));
        txtCostoAlojamiento.setBorder(null);
        txtCostoAlojamiento.setCaretColor(new java.awt.Color(220, 95, 0));
        txtCostoAlojamiento.setOpaque(false);
        jPanel1.add(txtCostoAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 270, 40));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 48, 36));

        jSeparator4.setBackground(new java.awt.Color(207, 10, 10));
        jSeparator4.setForeground(new java.awt.Color(220, 95, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 10));

        txaDatosExtra.setColumns(20);
        txaDatosExtra.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txaDatosExtra.setRows(5);
        txaDatosExtra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL EXTRA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jScrollPane1.setViewportView(txaDatosExtra);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 310, 120));

        tblDatos.setAutoCreateRowSorter(true);
        tblDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDatos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.setGridColor(new java.awt.Color(220, 95, 0));
        tblDatos.setOpaque(false);
        tblDatos.setRowHeight(30);
        tblDatos.setSelectionBackground(new java.awt.Color(220, 95, 0));
        jScrollPane2.setViewportView(tblDatos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 640, 280));

        jLabel23.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(10, 10, 10));
        jLabel23.setText("NUMERO DE HABITACIONES");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtNumeroHabitaciones.setBackground(new java.awt.Color(33, 45, 62));
        txtNumeroHabitaciones.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtNumeroHabitaciones.setForeground(new java.awt.Color(220, 95, 0));
        txtNumeroHabitaciones.setBorder(null);
        txtNumeroHabitaciones.setCaretColor(new java.awt.Color(220, 95, 0));
        txtNumeroHabitaciones.setOpaque(false);
        jPanel1.add(txtNumeroHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 270, 40));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 48, 36));

        jSeparator5.setBackground(new java.awt.Color(207, 10, 10));
        jSeparator5.setForeground(new java.awt.Color(220, 95, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 310, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrear;
    public javax.swing.JComboBox<String> cbxIdHotel;
    public javax.swing.JComboBox<String> cbxPortadaPrincipal;
    public javax.swing.JComboBox<String> cbxPortadaSecundaria;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel lblPortadaPrincipal;
    public javax.swing.JLabel lblPortadaSecundaria;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextArea txaDatosExtra;
    public javax.swing.JTextField txtCostoAlojamiento;
    public javax.swing.JTextField txtNumeroHabitaciones;
    public javax.swing.JTextField txtNumeroPersonas;
    // End of variables declaration//GEN-END:variables
}
