/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

/**
 *
 * @author yanni
 */
public class VListar extends javax.swing.JInternalFrame {

    /**
     * Creates new form VRegistro
     */
    public VListar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMostrarEntidad = new javax.swing.ButtonGroup();
        bgMostrarInformacion = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rbAlojamiento = new javax.swing.JRadioButton();
        rbUsuarios = new javax.swing.JRadioButton();
        rbPaquetes = new javax.swing.JRadioButton();
        rbActividades = new javax.swing.JRadioButton();
        rbHoteles = new javax.swing.JRadioButton();
        rbVuelos = new javax.swing.JRadioButton();
        rbAviones = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rbTodaInformacion = new javax.swing.JRadioButton();
        rbResumen = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        txtParametro = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        cbxFiltro = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDatos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.setGridColor(new java.awt.Color(220, 95, 0));
        tblDatos.setOpaque(false);
        tblDatos.setRowHeight(30);
        tblDatos.setSelectionBackground(new java.awt.Color(220, 95, 0));
        jScrollPane1.setViewportView(tblDatos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1140, 380));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOSTRAR ENTIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMostrarEntidad.add(rbAlojamiento);
        rbAlojamiento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbAlojamiento.setText("Alojamientos");
        rbAlojamiento.setOpaque(false);
        jPanel1.add(rbAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 150, -1));

        bgMostrarEntidad.add(rbUsuarios);
        rbUsuarios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbUsuarios.setText("Usuarios");
        rbUsuarios.setOpaque(false);
        jPanel1.add(rbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        bgMostrarEntidad.add(rbPaquetes);
        rbPaquetes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbPaquetes.setText("Paquetes");
        rbPaquetes.setOpaque(false);
        jPanel1.add(rbPaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, -1));

        bgMostrarEntidad.add(rbActividades);
        rbActividades.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbActividades.setText("Actividades");
        rbActividades.setOpaque(false);
        jPanel1.add(rbActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 150, -1));

        bgMostrarEntidad.add(rbHoteles);
        rbHoteles.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbHoteles.setText("Hoteles");
        rbHoteles.setOpaque(false);
        jPanel1.add(rbHoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 150, -1));

        bgMostrarEntidad.add(rbVuelos);
        rbVuelos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbVuelos.setText("Vuelos");
        rbVuelos.setOpaque(false);
        jPanel1.add(rbVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 150, -1));

        bgMostrarEntidad.add(rbAviones);
        rbAviones.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbAviones.setText("Aviones");
        rbAviones.setOpaque(false);
        jPanel1.add(rbAviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 150, -1));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOSTRAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton8.setText("Alojamientos");
        jRadioButton8.setOpaque(false);
        jPanel2.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 150, -1));

        jRadioButton9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton9.setText("Usuarios");
        jRadioButton9.setOpaque(false);
        jPanel2.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jRadioButton10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton10.setText("Paquetes");
        jRadioButton10.setOpaque(false);
        jPanel2.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, -1));

        jRadioButton11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton11.setText("Actividades");
        jRadioButton11.setOpaque(false);
        jPanel2.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 150, -1));

        jRadioButton12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton12.setText("Hoteles");
        jRadioButton12.setOpaque(false);
        jPanel2.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 150, -1));

        jRadioButton13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton13.setText("Vuelos");
        jRadioButton13.setOpaque(false);
        jPanel2.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 150, -1));

        jRadioButton14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton14.setText("Aviones");
        jRadioButton14.setOpaque(false);
        jPanel2.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1140, 70));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1140, 70));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTAR INFORMACION");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1140, 40));

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOSTRAR INFORMACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 16))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMostrarInformacion.add(rbTodaInformacion);
        rbTodaInformacion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbTodaInformacion.setText("Tota la informacion");
        rbTodaInformacion.setOpaque(false);
        jPanel5.add(rbTodaInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        bgMostrarInformacion.add(rbResumen);
        rbResumen.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        rbResumen.setText("Resumen");
        rbResumen.setOpaque(false);
        jPanel5.add(rbResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, -1));

        jPanel6.setBackground(new java.awt.Color(250, 250, 250));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOSTRAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 16))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton29.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton29.setText("Alojamientos");
        jRadioButton29.setOpaque(false);
        jPanel6.add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 150, -1));

        jRadioButton30.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton30.setText("Usuarios");
        jRadioButton30.setOpaque(false);
        jPanel6.add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jRadioButton31.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton31.setText("Paquetes");
        jRadioButton31.setOpaque(false);
        jPanel6.add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, -1));

        jRadioButton32.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton32.setText("Actividades");
        jRadioButton32.setOpaque(false);
        jPanel6.add(jRadioButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 150, -1));

        jRadioButton33.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton33.setText("Hoteles");
        jRadioButton33.setOpaque(false);
        jPanel6.add(jRadioButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 150, -1));

        jRadioButton34.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton34.setText("Vuelos");
        jRadioButton34.setOpaque(false);
        jPanel6.add(jRadioButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 150, -1));

        jRadioButton35.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jRadioButton35.setText("Aviones");
        jRadioButton35.setOpaque(false);
        jPanel6.add(jRadioButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 150, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1140, 70));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 310, 70));

        txtParametro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        txtParametro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PARAMETRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 16))); // NOI18N
        jPanel3.add(txtParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 230, 70));

        btnBuscar.setBackground(new java.awt.Color(250, 250, 250));
        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setOpaque(true);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 320, 60));

        cbxFiltro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FILTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 16))); // NOI18N
        jPanel3.add(cbxFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 250, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMostrarEntidad;
    private javax.swing.ButtonGroup bgMostrarInformacion;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JComboBox<String> cbxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton rbActividades;
    public javax.swing.JRadioButton rbAlojamiento;
    public javax.swing.JRadioButton rbAviones;
    public javax.swing.JRadioButton rbHoteles;
    public javax.swing.JRadioButton rbPaquetes;
    public javax.swing.JRadioButton rbResumen;
    public javax.swing.JRadioButton rbTodaInformacion;
    public javax.swing.JRadioButton rbUsuarios;
    public javax.swing.JRadioButton rbVuelos;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtParametro;
    // End of variables declaration//GEN-END:variables
}
