/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

/**
 *
 * @author yanni
 */
public class VSelecionarActividad extends javax.swing.JInternalFrame {

    /**
     * Creates new form VSelecionarAlojamiento
     */
    public VSelecionarActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblPortadoPrincipal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cbxMisPaquetes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDatosExtra = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        txtIdActividad = new javax.swing.JTextField();
        txtNombreActividad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtIdCategoria = new javax.swing.JTextField();
        txtCostoActividad = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lblPortadaSecundaria = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblCantidadRegistros = new javax.swing.JLabel();
        lblNombreActividad = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnRight.setBackground(new java.awt.Color(33, 45, 62));
        btnRight.setForeground(new java.awt.Color(250, 250, 250));
        btnRight.setText(">");
        btnRight.setContentAreaFilled(false);
        btnRight.setOpaque(true);
        jPanel1.add(btnRight, java.awt.BorderLayout.LINE_END);

        btnLeft.setBackground(new java.awt.Color(33, 45, 62));
        btnLeft.setForeground(new java.awt.Color(250, 250, 250));
        btnLeft.setText("<");
        btnLeft.setContentAreaFilled(false);
        btnLeft.setOpaque(true);
        jPanel1.add(btnLeft, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(207, 10, 10));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PORTADA PRINCIPAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(lblPortadoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 510, 250));

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxMisPaquetes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        cbxMisPaquetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxMisPaquetes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MIS PAQUETES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel4.add(cbxMisPaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 490, 60));

        txaDatosExtra.setColumns(20);
        txaDatosExtra.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txaDatosExtra.setRows(5);
        txaDatosExtra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL EXTRA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jScrollPane1.setViewportView(txaDatosExtra);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 490, 190));

        jPanel2.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        txtIdActividad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtIdActividad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID ACTIVIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel7.add(txtIdActividad);

        txtNombreActividad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtNombreActividad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE ACTIVIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel7.add(txtNombreActividad);

        txtDescripcion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIPCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel7.add(txtDescripcion);

        txtIdCategoria.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtIdCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel7.add(txtIdCategoria);

        txtCostoActividad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtCostoActividad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COSTO ACTIVIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel7.add(txtCostoActividad);

        jPanel2.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PORTADA SECUNDARIA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(lblPortadaSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 510, 250));

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        btnAgregar.setBackground(new java.awt.Color(33, 45, 62));
        btnAgregar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(250, 250, 250));
        btnAgregar.setText("AGREGAR ACTIVIDAD");
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setOpaque(true);
        jPanel1.add(btnAgregar, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));
        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("jLabel1");
        jPanel5.add(lblTitulo);

        jPanel9.setBackground(new java.awt.Color(250, 250, 250));
        jPanel9.setLayout(new java.awt.GridLayout(1, 3));

        lblCantidadRegistros.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblCantidadRegistros.setForeground(new java.awt.Color(207, 10, 10));
        lblCantidadRegistros.setText("jLabel2");
        jPanel9.add(lblCantidadRegistros);

        lblNombreActividad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblNombreActividad.setForeground(new java.awt.Color(207, 10, 10));
        lblNombreActividad.setText("jLabel2");
        jPanel9.add(lblNombreActividad);

        lblUsuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(207, 10, 10));
        lblUsuario.setText("jLabel2");
        jPanel9.add(lblUsuario);

        jPanel5.add(jPanel9);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnLeft;
    public javax.swing.JButton btnRight;
    public javax.swing.JComboBox<String> cbxMisPaquetes;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblCantidadRegistros;
    public javax.swing.JLabel lblNombreActividad;
    public javax.swing.JLabel lblPortadaSecundaria;
    public javax.swing.JLabel lblPortadoPrincipal;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lblUsuario;
    public javax.swing.JTextArea txaDatosExtra;
    public javax.swing.JTextField txtCostoActividad;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtIdActividad;
    public javax.swing.JTextField txtIdCategoria;
    public javax.swing.JTextField txtNombreActividad;
    // End of variables declaration//GEN-END:variables
}
