/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

/**
 *
 * @author yanni
 */
public class VVerPaquetes extends javax.swing.JInternalFrame {

    /**
     * Creates new form VSelecionarAlojamiento
     */
    public VVerPaquetes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLienzo = new javax.swing.JPanel();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblPaquete = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblAlojamiento = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblVuelo = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblActividad = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaDatosPaquete = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDatosAlojamiento = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDatosVuelo = new javax.swing.JTextArea();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDatosActividad = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblCantidadRegistros = new javax.swing.JLabel();
        lblNombrePaquete = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();

        setClosable(true);

        pLienzo.setBackground(new java.awt.Color(250, 250, 250));
        pLienzo.setLayout(new java.awt.BorderLayout());

        btnRight.setBackground(new java.awt.Color(33, 45, 62));
        btnRight.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnRight.setForeground(new java.awt.Color(250, 250, 250));
        btnRight.setText(">");
        btnRight.setContentAreaFilled(false);
        btnRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRight.setOpaque(true);
        pLienzo.add(btnRight, java.awt.BorderLayout.LINE_END);

        btnLeft.setBackground(new java.awt.Color(33, 45, 62));
        btnLeft.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnLeft.setForeground(new java.awt.Color(250, 250, 250));
        btnLeft.setText("<");
        btnLeft.setContentAreaFilled(false);
        btnLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeft.setOpaque(true);
        pLienzo.add(btnLeft, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(207, 10, 10));
        jPanel2.setLayout(new java.awt.GridLayout(2, 4, 1, 1));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAQUETE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));
        jPanel9.add(lblPaquete);

        jPanel2.add(jPanel9);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALOJAMIENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));
        jPanel12.add(lblAlojamiento);

        jPanel2.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VUELO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));
        jPanel13.add(lblVuelo);

        jPanel2.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACTIVIDAD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));
        jPanel14.add(lblActividad);

        jPanel2.add(jPanel14);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL PAQUETE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        txaDatosPaquete.setColumns(20);
        txaDatosPaquete.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaDatosPaquete.setRows(5);
        jScrollPane4.setViewportView(txaDatosPaquete);

        jPanel4.add(jScrollPane4);

        jPanel2.add(jPanel4);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS ALOJAMIENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        txaDatosAlojamiento.setColumns(20);
        txaDatosAlojamiento.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaDatosAlojamiento.setRows(5);
        jScrollPane1.setViewportView(txaDatosAlojamiento);

        jPanel15.add(jScrollPane1);

        jPanel2.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS VUELO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        txaDatosVuelo.setColumns(20);
        txaDatosVuelo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaDatosVuelo.setRows(5);
        jScrollPane2.setViewportView(txaDatosVuelo);

        jPanel16.add(jScrollPane2);

        jPanel2.add(jPanel16);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS ACTIVIDAD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        txaDatosActividad.setColumns(20);
        txaDatosActividad.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaDatosActividad.setRows(5);
        jScrollPane3.setViewportView(txaDatosActividad);

        jPanel17.add(jScrollPane3);

        jPanel2.add(jPanel17);

        pLienzo.add(jPanel2, java.awt.BorderLayout.CENTER);

        btnAgregar.setBackground(new java.awt.Color(33, 45, 62));
        btnAgregar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(250, 250, 250));
        btnAgregar.setText("AGREGAR AL CARRITO");
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setOpaque(true);
        pLienzo.add(btnAgregar, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("jLabel1");
        jPanel1.add(lblTitulo);

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        lblCantidadRegistros.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblCantidadRegistros.setForeground(new java.awt.Color(207, 10, 10));
        lblCantidadRegistros.setText("jLabel2");
        jPanel5.add(lblCantidadRegistros);

        lblNombrePaquete.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblNombrePaquete.setForeground(new java.awt.Color(207, 10, 10));
        lblNombrePaquete.setText("jLabel2");
        jPanel5.add(lblNombrePaquete);

        lblEmail.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(207, 10, 10));
        lblEmail.setText("jLabel2");
        jPanel5.add(lblEmail);

        jPanel1.add(jPanel5);

        pLienzo.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 1294, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnLeft;
    public javax.swing.JButton btnRight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel lblActividad;
    public javax.swing.JLabel lblAlojamiento;
    public javax.swing.JLabel lblCantidadRegistros;
    public javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblNombrePaquete;
    public javax.swing.JLabel lblPaquete;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lblVuelo;
    public javax.swing.JPanel pLienzo;
    public javax.swing.JTextArea txaDatosActividad;
    public javax.swing.JTextArea txaDatosAlojamiento;
    public javax.swing.JTextArea txaDatosPaquete;
    public javax.swing.JTextArea txaDatosVuelo;
    // End of variables declaration//GEN-END:variables
}
